name: Auto Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            echo "Starting deployment process..."

            cd ~/sniff-step-nest
            git pull origin main
            docker-compose --profile service build
            docker-compose --profile service down
            docker-compose --profile service up -d
            echo "Deployment completed successfully!"
